version: '3'

services:
 
 
  
  cardschemeconsumer:
    image: austine234/cardschemeconsumer
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

   
      
  
  